#! /bin/bash

export LC_ALL='C';
files="$(find $1 -maxdepth 1 -type f | sort)"
for file in $files
do
    for file2 in $files
    do
        if [ "$file" != "$file2" ]
        then
     	    diff=$(comm -3 -- "$file" "$file2");
      	    if [[ -z $diff ]]
       	        then
		    rm -- "$file2";
		    ln -- "$file" "$file2";
     	    fi
        fi
    done
done
